definitions/json/CaseEvent.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1084
Merge ECM R5.0.24
```
[ ] Yes
[x] No
```

Merge ECM R5.0.24

---

package.json

Update local host

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-879
Add initGenerateReport callback to populate Clerks
```
[ ] Yes
[x] No
```

Add initGenerateReport callback

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1189
Merge ECM R5.0.25
```
[ ] Yes
[x] No
```

Merge ECM R5.0.25

---

definitions/json/Scotland Scrubbed.json

added new ecc report

---

definitions/json/Scotland Scrubbed.json

Ecm 553 added new ecc report

---

definitions/json/ComplexTypes.json

Revert BF report field type changes
```
[ ] Yes
[x] No
```

Revert BF report field type changes

---

definitions/json/CaseEventToFields.json
definitions/json/ComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1436
ECM R5.0.26
```
[ ] Yes
[x] No
```

ECM R5.0.26

---

definitions/json/CaseEventToFields.json

new mid event added

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json

https://github.com/hmcts/et-ccd-definitions-englandwales/pull/43
Merge ECM R5.0.27
```
[ ] Yes
[x] No
```

ECM R5.0.27

---

definitions/json/Scotland Scrubbed.json

Config changes for ecm-664.
```
[ ] Yes
[ x ] No
```

config change update for ecm-664

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1463
Update CCD config to include sex and gender identity fields (Scotland)
```
[ ] Yes
[x] No
```

[RET-1463] update ccd config: sex and gender identity (scotland)

---

definitions/json/State.json

Add Submitted state title display back in after it was accidentally removed
```
[ ] Yes
[x] No
```

Add Submitted title display back in

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json
yarn.lock

https://tools.hmcts.net/jira/browse/RET-1471
Added Claimant Hearing Preference case field and complex type. Changed claimant_average_weekly_hours type from text to number (ticket https://tools.hmcts.net/jira/browse/RET-1464).
```
[ ] Yes
[X] No
```

Ret 1471 - Claimant hearing preference

---

definitions/json/CaseTypeTab.json

table view added for hearingsCollection

---

definitions/json/CaseTypeTab.json

Fix DisplayContextParameter for Hearings table
```
[ ] Yes
[x] No
```

Fix DisplayContextParameter for Hearings table

---

definitions/json/State.json

https://tools.hmcts.net/jira/browse/RET-1466
Remove "Draft" state in favour of "AWAITING_SUBMISSION_TO_HMCTS" state.
```
[ ] Yes
[x] No
```

RET-1466. Remove "Draft" state.

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-1983
Merge ECM R5.0.31 Add reasonable adjustment flag
```
[ ] Yes
[x] No
```

Merge ECM R5.0.31

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

Merge main conflicts

---

definitions/json/CaseEventToFields.json

Fix Type of Claim

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2041
"Has the case been disposed?" question in Hearing Details should be mandatory
```
[ ] Yes
[x] No
```

"Has the case been disposed?" should be mandatory

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

(https://tools.hmcts.net/jira/browse/RET-1841)
Case worker has commenced vetting process for a new ET1 case.
This story is for the Case worker (having assessed the information contained in the ET1 form and Acas certificate) to note details of any possible substantive defects that may apply to the claim, as part of the ET1 Vetting process
User Story
As a Admin/case worker I want to note any possible substantive defects that may apply to the claim so that I am able to continue with the ET1 vetting process
```
[ ] Yes
[ x] No
```

RET-1841: ET1 Vetting - Substantive defects

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2054
Added 'Select Respondent' page for ET3 Vetting
```
[ ] Yes
[x] No
```

Ret 2054: Added 'Select Respondent' page for ET3 Vetting

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2040
```
[ ] Yes
[X ] No
```

New midEventCallBack added

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2024
Fixed permissions on 2024
```
[ ] Yes
[x] No
```

Ret 2024: Fix permissions on date labels

---

definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2032
Fixed optional fields and page show conditions
```
[ ] Yes
[x] No
```

Ret 2032: Fixed optional fields and page show conditions

---

definitions/json/CaseEventToFields.json
definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2067
Added extension fields to Respondent details
```
[ ] Yes
[x] No
```

RET-2067: Added Extension to respondentCollection complex type

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1982
Added 'Response in Time' Page for ET3 Vetting
```
[ ] Yes
[x] No
```

RET-1982: Added 'Response in Time' ET3 page

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2034
Added missing field authorisations
```
[ ] Yes
[ x ] No
```

RET-2034: Added missing authorizations

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-1852
Fixes a strange behaviour of the multi select list.
```
[ ] Yes
[ x] No
```

RET-1852: Fixes strange behaviour of the multi select list

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1846
Further questions page for vetting process.
```
[ ] Yes
[x] No
```

RET-1846. Further questions page.

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1989
https://tools.hmcts.net/jira/browse/RET-1990
Added ET3 "Resist the Claim" and "Employer Contract Claim" pages
```
[ ] Yes
[x] No
```

Added ET3 "Resist the Claim" and "Employer Contract Claim" pages

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1991
https://tools.hmcts.net/jira/browse/RET-2001
Added ET3 pages for Case Listed and Transfer Application
```
[ ] Yes
[x] No
```

Added ET3 pages for Case Listed and Transfer Application

---

definitions/json/CaseEvent.json

Temporary changes for testing ET1 vetting jurisdiction code

---

definitions/json/ComplexTypes.json
definitions/json/Scotland Scrubbed.json

to the ET1 journey
https://tools.hmcts.net/jira/browse/RET-1842
```
[ ] Yes
[x ] No
```

RET-1842: New dynamic list for only the jur codes applicable

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-1849
Add a post-vetting event page with next steps.
```
[ ] Yes
[x] No
```

RET-1849. Add post vetting event.

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1842
```
[ ] Yes
[x ] No
```

RET-1842: Fixed defects

---

definitions/json/AuthorisationCaseField.json

Fixed permissions for ET3 vetting
```
[ ] Yes
[ ] No
```

ET3 Permission Tidy

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-1845
Add suggest hearing venue page.
```
[ ] Yes
[x] No
```

RET-1845. Add suggest hearing venue page.

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2019
https://tools.hmcts.net/jira/browse/RET-2019
```
[ ] Yes
[✓] No
```

RET-2019: CYA page for ET3 Vetting

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

Grouped Et3 fields together for ET3 journey cleanup
```
[ ] Yes
[x] No
```

Grouping ET3 fields together

---

definitions/json/ComplexTypes.json

Hotfix for missing et3GeneralNotesCompanyHouse
```
[ ] Yes
[x] No
```

Hotfix for missing et3GeneralNotesCompanyHouse

---

definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-2151
```
[ ] Yes
[x ] No
```

RET-2151: ET1 Vetting - Display saved data in ECM tab

---

definitions/json/CaseEvent.json

ET3 Vetting Rename
```
[ ] Yes
[ ] No
```

ET3 Vetting rename

---

definitions/json/CaseEventToFields.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2160
```
[ ] Yes
[X] No
```

RET-2160 fields removed

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2161
```
[ ] Yes
[x ] No
```

RET-2161: ET1 Serving - Show Send Documents and Send to Acas

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2165
```
[ ] Yes
[X] No
```

RET-2165 delete rights removed for jurCodesCollection

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1903
https://tools.hmcts.net/jira/browse/RET-1904
https://tools.hmcts.net/jira/browse/RET-1908
https://tools.hmcts.net/jira/browse/RET-1909
Added pages 1903, 1904, 1908 and 1909
```
[ ] Yes
[x] No
```

Added up to RET-1909

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1910
https://tools.hmcts.net/jira/browse/RET-1911
https://tools.hmcts.net/jira/browse/RET-1912
https://tools.hmcts.net/jira/browse/RET-1914
https://tools.hmcts.net/jira/browse/RET-1915
Added 1910, 1911, 1912, 1914 and 1915
```
[ ] Yes
[x] No
```

Added up to 1915

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/EventToComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1916
https://tools.hmcts.net/jira/browse/RET-1917
https://tools.hmcts.net/jira/browse/RET-1918
https://tools.hmcts.net/jira/browse/RET-1946
https://tools.hmcts.net/jira/browse/RET-1947
https://tools.hmcts.net/jira/browse/RET-1948
Added rest of ET3 Response
```
[ ] Yes
[x] No
```

Added rest of ET3 Response

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

Changed YesOrNo to fixed radio list for claimant job details
```
[ ] Yes
[x] No
```

Changed YesOrNo to fixed radio list for claimant job details

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2197
Added new field for MyHMCTS and reordered respondent rep page
```
[ ] Yes
[X] No
```

added organisation complex type to respondent representative

---

definitions/json/AuthorisationCaseField.json

User role fix

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

https://tools.hmcts.net/jira/browse/RET-2197
Adding auths for legalrep-solicitor
```
[ ] Yes
[x] No
```

legalrep-solicitor authorisations

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

Change caseworker-ET-pcqextractor role to be lowercase so that it is consistent with all other roles
```
[ ] Yes
[x] No
```

Fix case of caseworker-ET-pcqextractor role

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

Merge update caseworker-ET-pcqextractor role
```
[ ] Yes
[x] No
```

Merge update caseworker-ET-pcqextractor role

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2221
Fixed issues not showing in CYA 
```
[ ] Yes
[x] No
```

fixes CYA issues not showing

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2214
Added text area to rule 27 No jurisdiction
Increment page Order
```
[ ] Yes
[x ] No
```

added text area for no jurisdiction

---

definitions/json/CaseEvent.json

RET-2238: ET1 case vetting now available on states: Rejected;Vetted
```
[ ] Yes
[x] No
```

RET-2238: ET1 case vetting now available on states: Rejected;Vetted

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2214
Fixed Rule 27 No reasonable prospect set out reason
```
[ ] Yes
[x ] No
```

added No reasonable prospect of success - Set out reason

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-1934
Add missing fields for new employment type
```
[ ] Yes
[x] No

Add new job types

---

package.json

https://tools.hmcts.net/jira/browse/RET-1835
Add generate-excel-preview
```
[ ] Yes
[x] No
```

Add generate-excel-preview

---

package.json

Add script to build CCD definitions for use in preview environment
```
[ ] Yes
[x] No
```

Add preview environment script

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2260
Add Hublinks to the update draft case event and to the CCD config.
```
[ ] Yes
[x] No
```

RET-2260. Add hublinks complex field.

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-1454
Added callback URLs to SUBMIT_CASE_DRAFT in CaseEvent.json on lines 43 & 44.
```
[ ] Yes
[X] No
```

Ret-1454 handle logic upon case submission

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1937
Adding necessary fields
```
[ ] Yes
[x] No
```

Ret 1937 - Claim Details

---

definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json

https://tools.hmcts.net/jira/browse/RET-2528
Removed ACAS role from certain case states and fields
```
[ ] Yes
[X] No
```

Removing ACAS perms

---

definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2072
```
[ ] Yes
[ x] No
```

RET-2072: Adding new Rejection of Claim field to Upload Document event

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2538
Allow a submitted case's details to be updated.
```
[ ] Yes
[x] No
```

RET-2538. Add event to update a submitted case's data.

---

definitions/json/AuthorisationCaseField.json

Updated ACAS perms
```
[ ] Yes
[ ] No
```

Acas Permissions

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2578
Bug fixes from final checks testing
Invalid date error message not displaying
Show ethosCaseReference for submitted claims
```
[ ] Yes
[ x] No
```

RET-2578: Add complexType 'other_claim'

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-1968
Add new typesOfClaim data using multiselect list
```
[ ] Yes
[x] No
```

Add types of claim

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-2603
```
[ ] Yes
[x ] No
```

Ret 2603 - Document alerts not present on Citizen-hub

---

definitions/json/CaseEvent.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2612
added aboutToSubmit callback for uploadDocument
```
[ ] Yes
[x] No
```

RET-2612: Email on case rejection document upload

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-1856
added callback for et1Serving submitted
```
[ ] Yes
[x] No
```

RET-1856: added callback for et1Serving submitted

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2639
add referral summary pdf
```
[ ] Yes
[X] No
```

2639: add referral summary pdf

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2063
ET3 Notification complete
```
[ ] Yes
[x] No
```

RET-2063: ET3 Notification complete

---

definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2273
Added Tribunal case file to fl_DocumentType
```
[] Yes
[x] No
```

RET-2273: CR: Add Tribunal case file to fl_DocumentType

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2323
CR: Add validation to the disposal date field at jurisdiction level
```
[] Yes
[x] No
```

RET-2323: CR: Add validation to the disposal date field at jurisdiction level

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2684
Changed Initial Consideration Before You Start label text
```
[] Yes
[x] No
```

RET-2684: Changed Initial Consideration Before You Start label text

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2685
Hiding and prefilling is hearing already listed question
```
[] Yes
[x] No
```

RET-2685: Hiding and prefilling is hearing already listed question

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-2590
Add a suggested hearing venue field to the case details tab
```
[] Yes
[x] No
```

RET-2590: Add a suggested hearing venue field to the case details tab

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/WorkBasketInputFields.json
definitions/json/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/RET-2275
```
[ ] Yes
[X] No
```

ret-2275 implementation

---

definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2796
Added Vacated option
```
[ ] Yes
[ ] No
```

RET-2796 Added vacated option

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2839
```
[ ] Yes
[X] No
```

ACAS email correction

---

definitions/json/Scotland Scrubbed.json

RET-2574: Fix unassigned value

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/AuthorisationCaseState.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ChallengeQuestion.json
definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json
package.json
src/main/lib/substitutor.js

https://tools.hmcts.net/jira/browse/RET-2841
```
[ ] Yes
[x] No
```

notice of change for Scotland

---

definitions/json/ChallengeQuestion.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2994
```
[ ] Yes
[x ] No
```

RET-2994 added NOC challange questions

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2994
```
[ ] Yes
[x ] No
```

RET-2994 removed duplicate

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3047
Fixed Authorisations for ET3 Response Form
```
[] Yes
[x] No
```

RET-3047: Fixed Authorisations for ET3 Response Form

---

definitions/json/AuthorisationCaseEvent.json

Revert shutter ET3

---

definitions/json/AuthorisationCaseEvent.json

Corrected case type id

---

.github/dependabot.yml
definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/Scotland Scrubbed.json
package.json
yarn.lock

Release 1.1.2

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2617
Renaming to match frontend, data model, callbacks.
```
[ ] Yes
[X] No
```

RET-2617 - Renaming Rule 92 fields

---

definitions/json/Scotland Scrubbed.json

Pet 1.1.0.6

---

package.json

Add generate-excel-ithc
```
[ ] Yes
[x] No
```

Add ITHC env

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2949
Deleted additional letter question from send notification
```
[] Yes
[x] No
```

RET-2949: Deleted additional letter question from send notification

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-2949
Fixed Full Name under Case Management Orders / Request
```
[] Yes
[x] No
```

RET-2949: Fixed Full Name under Case Management Orders / Request

---

definitions/json/AuthorisationCaseField.json

Add TSE doc missing role

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3026
https://tools.hmcts.net/jira/browse/RET-2867
```
[ ] Yes
[ ] No
```

RET-3026 Select Application to view 

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3174
```
[ ] Yes
[x ] No
```

RET-3174 added read permissions for et-acas-api

---

definitions/json/AuthorisationCaseField.json

Removing duplicated entry

---

definitions/json/WorkBasketInputFields.json

[RET-3235](https://tools.hmcts.net/jira/browse/RET-3235)
Added 2 new search fields as Claimant Surname, Claimant First Name in WorkBasketInputFields
-----
```
[ ] Yes
[X] No
```

Ret-3235 Add new case list search filters, Claimant Surname & Claimant First Name

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3116
```
[ ] Yes
[X] No
```

Ret 3116 dateformat

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

RET-3117 added new fields

---

definitions/json/CaseField.json

revert field data type

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3026
```
[ ] Yes
[ ] No
```

RET-3026 add about to start callback URL

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2953
```
[ ] Yes
[x ] No
```

RET-2953 added respond to a notification event

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3048
View all Judgement, Orders and Notification
```
[] Yes
[x] No
```

RET-3048: View all Judgement, Orders and Notification

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3255
RET-3255: Fixed ET3 Response form Contest Claim field type
```
[] Yes
[x] No
```

RET-3255: RET-3255: Fixed ET3 Response form Contest Claim field type

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3244
Add application state
```
[ ] Yes
[x] No
```

RET-3244 - Add application state

---

definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2949
Various fixes for 2949
```
[] Yes
[x] No
```

RET-2949: Various fixes for 2949

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3250
Hide application state
```
[ ] Yes
[x] No
```

RET-3250 - Hide application state

---

definitions/json/CaseEvent.json

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RET-3314
Change description
Added Response Complete functionality
Does this PR introduce a breaking change? (check one with "x")

RET-3314: Add Close Application Submit

---

package.json

Updated preview links

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-3333
```
[ ] Yes
[x] No
```

RET-3333 Make upload mandatory when add new document is selected

---

definitions/json/CaseEventToFields.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3364
```
[ ] Yes
[x] No
```

RET-3364 sendUploadNotificationDoc mandatory fix

---

definitions/json/CaseEventToFields.json

RET-3332: Fix for field not appearing

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2948
Added notifications tab
```
[] Yes
[x] No
```

RET-2948: Added notifications tab

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3352
Added permissions for Legal Rep
```
[ ] Yes
[x] No
```

RET-3352: Add Legal Rep Permissions

---

definitions/json/AuthorisationCaseField.json

Ret 2982 new field access

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

Missing Scotland Field

---

definitions/json/Scotland Scrubbed.json

RET-3347 master

---

definitions/json/AuthorisationCaseField.json

RET-3395: Hide Referrals, ET1 Vetting, History tabs for legal rep

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

Fix whitespaces
```
[ ] Yes
[x] No
```

Fix whitespaces

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-2948
Added tribunal responses to notifications tab
```
[] Yes
[x] No
```

RET-2948: Added tribunal responses to notifications tab

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3106
Added page 3 of Bundles Respondent journey
```
[] Yes
[x] No
```

RET-3106: Added page 3 of Bundles Respondent journey

---

package.json

N/A
Update preview link for Release 2.0
```
[ ] Yes
[x] No
```

Update preview link for Release 2.0

---

definitions/json/CaseEventToFields.json

Managing office display added in the "Generate Report" event.
https://tools.hmcts.net/jira/browse/RET-3474
```
[ ] Yes
[X] No
```

Managing office display added

---

definitions/json/CaseEvent.json

RET-3438: Fix for NOC email is not being sent to Removed Organisation

---

env.json

fix merge conf

---

env.json

revert to old env var names

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3553
Hide non-MyHMCTS fields from respondent representative
```
[ ] Yes
[X] No
```

RET-3553. Hide non-MyHMCTS fields from respondent representative

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3085
Added submitted page for respondent bundles
```
[] Yes
[x] No
```

RET-3085: Added submitted page for respondent bundles

---

definitions/json/ComplexTypes.json

Fix Field not recognised on Respond to Notification
```
[] Yes
[x] No
```

RET-0000: Fix Field not recognised on Respond to Notification

---

definitions/json/AuthorisationCaseField.json
definitions/json/WorkBasketResultFields.json

RET-2592-bug-fix: Hide Referral tab for legal rep

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2435
```
[ ] Yes
[ ] No
```

Ret 2435 Create "IssueInitialConsiderationDirections" Task for Admin

---

definitions/json/CaseEvent.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-2347
Publish Event and Fields needed for Work Allocation
```
[ ] Yes
[x] No
```

Ret 2347 - Create Task "ReviewReferralAdmin" for Admin

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2379
https://tools.hmcts.net/jira/browse/RET-2380
https://tools.hmcts.net/jira/browse/RET-2381
This story deals with the automated creation of "ReviewReferralResponseAdmin" task following a referral event
```
[ ] Yes
[x] No
```

Ret 2379 review referral response admin

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2444
https://tools.hmcts.net/jira/browse/RET-2445
https://tools.hmcts.net/jira/browse/RET-2446
Create "DraftAndSignJudgment" Task for Judge
```
[ ] Yes
[x] No
```

RET-2444: Create "DraftAndSignJudgment" Task for Judge

---

definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3662
Updated config to move link to document event rather than link
```
[ ] Yes
[x] No
```

Ret 3662 document event

---

definitions/json/CaseField.json

Reverts hmcts/et-ccd-definitions-scotland#413

Revert "RET-3662 - Fix Broken Link"

---

definitions/json/ComplexTypes.json

Show address

---

definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3760
make field optional
```
[ ] Yes
[x] No
```

RET-3760 short description on notification doc

---

definitions/json/CaseEventToFields.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3761
Amend shortDescription on uploadDocumentForServing.
```
[ ] Yes
[x] No
```

RET-3761 - Amend shortDescription on uploadDocumentForServing

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3596
Remove empty CallBackURLAboutToStartEvent
```
[ ] Yes
[X] No
```

remove empty CallBackURLAboutToStartEvent

---

definitions/json/AuthorisationCaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2658
RET-2658: Give role access to task
```
[ ] Yes
[x] No
```

RET-2658: Give role access to task

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

https://tools.hmcts.net/jira/browse/RET-2658
[RET-2658: Give role access to event/state/type](https://github.com/hmcts/et-ccd-definitions-englandwales/commit/19312adc02271d86684b9791c406fab5fd7e3c13)
```
[ ] Yes
[x] No
```

RET-2658: Give role access to event/state/type

---

definitions/json/AuthorisationCaseState.json

https://tools.hmcts.net/jira/browse/RET-2658
Remove duplicate State/Role
```
[ ] Yes
[x] No
```

RET-2658: Remove Duplicate

---

env.json

New Preview
```
[ ] Yes
[x] No
```

RET-3720: Return Preview links

---

definitions/json/CaseEvent.json
env.json

https://tools.hmcts.net/jira/browse/RET-3684
Make it easier to search based on the title in ExUI
```
[ ] Yes
[x] No
```

Update event name and description for easier search

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3720
Add authorisations to CaseFields
```
[ ] Yes
[x] No
```

RET-3720: Add Authorisation

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2515
Add HMCTSServiceId supplementary_data to cases
```
[] Yes
[x] No
```

RET-2515: Add HMCTSServiceId supplementary_data to cases

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3188
https://tools.hmcts.net/jira/browse/RET-3189
https://tools.hmcts.net/jira/browse/RET-3190
```
[ ] Yes
[ ] No
```

publish id updated

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3720
Authorise fields used in Conf DMN
```
[ ] Yes
[x] No
```

RET-3720: Authorisation to CaseData fields

---

definitions/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-3246
```
[ ] Yes
[X ] No
```

Ret 3246 Make an application CYA - Check your answers page has no application type

---

definitions/json/ComplexTypes.json

RET-3794: Relocated response required fields

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3667
Adjusted permissions on CaseFlags related fields/events
```
[] Yes
[x] No
```

RET-3667: Adjusted permissions on CaseFlags related fields/events

---

definitions/json/CaseField.json

RET-3794: set character limit to fields

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json

RET-3794: fix missing configs for scotland cases

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3767
Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag
```
[] Yes
[x] No
```

RET-3767: Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag

---

definitions/json/AuthorisationCaseField.json

[RET-3663 - Remove notifications tab for Legal Rep](https://tools.hmcts.net/jira/browse/RET-3663)
```
[ ] Yes
[x] No
```

RET-3663 - Remove notifications tab for Legal Rep

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3792
Add viewedByClaiamnt property
```
[ ] Yes
[x] No
```

RET-3792 - Add viewedByClaimant property

---

definitions/json/RoleToAccessProfiles.json

https://tools.hmcts.net/jira/browse/RET-3878
Modify solicitor roles
```
[ ] Yes
[x] No
```

RET-3878 - Modify solicitor roles

---

definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-3857
Add private hearing question as part of initial consideration, made changes to ComplexTypes.json and EventToComplexTypes.json
```
[ ] Yes
[X] No
```

RET-3857: Add private hearing question as part of initial consideration

---

definitions/json/CaseEventToFields.json
definitions/json/EventToComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-2501
https://tools.hmcts.net/jira/browse/RET-2502
https://tools.hmcts.net/jira/browse/RET-2503
Add publishes for Application and Response fields
Also remove duplicate "Rule 21"
```
[ ] Yes
[x] No
```

RET 2501: Amend party details responses

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2501
CLAIMANT_TSE_RESPOND was triggering an event when a claimant was viewing an Application
```
[ ] Yes
[x] No
```

RET-2501: Remove duplicate event Trigger

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-3773
Determine private hearing flag
```
[] Yes
[x] No
```

RET-3773: Determine private hearing flag

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-3602
Add case linking
```
[ ] Yes
[x] No
```

RET-3602 - Add case linking

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3602
Modify caseworker access
```
[ ] Yes
[x] No
```

RET-3602 - Modify caseworker access

---

definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json
definitions/json/RoleToAccessProfiles.json

N/A
For QA
```
[ ] Yes
[x] No
```

Add caseworker-ras-validation

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4096
```
[ ] Yes
[ ] No
```

RET-4096 cancelTask changes

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-2370
https://tools.hmcts.net/jira/browse/RET-2373
Fix Typo
```
[ ] Yes
[x] No
```

RET-2370: Fix Typo

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-3820
https://tools.hmcts.net/jira/browse/RET-4081
Send case linking email
```
[ ] Yes
[x] No
```

RET-3820 + RET-4081 - Send case linking email

---

definitions/json/EventToComplexTypes.json

n/a
Duplicated code
```
[ ] Yes
[x] No
```

RET-0000: Remove Dupe

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4095
Add Publish to Events in Completion DMN
```
[ ] Yes
[x] No
```

RET-4095: Publish Complete Events

---

definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-3910
```
[ ] Yes
[X] No
```

RET-3910 - order change

---

definitions/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4095
Add more Completion events
```
[ ] Yes
[x] No
```

RET-4095: Publish Completion Events

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json
definitions/json/EventToComplexTypes.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-4019
```
[ ] Yes
[x] No
```

RET-4019 Hearing unavailability dates

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3514
Allow Non System Users Respond to an Application
```
[ ] Yes
[X] No
```

RET0-3514 Allow Non System Users Respond to an Application

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4169
https://tools.hmcts.net/jira/browse/RET-4170
Added new event for ACAS Cert lookup
Added ACAS Cert regex to fields
Made feeGroupReference optional
```
[ ] Yes
[X] No
```

RET-4169, RET-4170

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-3607
Add read permission to legal rep
```
[ ] Yes
[x] No
```

Add read permission to legal rep

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-4019
```
[ ] Yes
[x] No
```

RET-4019 add hearing unavailability tab

---

definitions/json/AuthorisationCaseField.json
definitions/json/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4122
```
[ ] Yes
[x] No
```

RET-4122 add caseManagementLocationCode

---

definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4021
RET-4021: Display notification banner on tribunal notification responses
```
[] Yes
[x] No
```

RET-4021: Display notification banner on tribunal notification responses

---

definitions/json/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-3891
added fl_DocumentType, Tse admin correspondence to scotland scrubbed json file
```
[ ] Yes
[X] No
```

RET-3891 Tribunal Respond to Application Create PDF file

---

definitions/json/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4024
Add permission for judges
```
[ ] Yes
[x] No

RET-4024 - Add permission for judges

---

definitions/json/CaseEvent.json
definitions/json/CaseField.json

fix master merge
```
[] Yes
[x] No
```

RET-0000: fix master merge

---

definitions/json/AuthorisationCaseState.json
definitions/json/AuthorisationCaseType.json

n/a
Add most recent Global Search config

Release 2.1 merge master

---

definitions/json/RoleToAccessProfiles.json

Fix ES Creator Issue

---

definitions/json/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField.json
definitions/json/CaseEvent.json
definitions/json/CaseEventToFields.json
definitions/json/CaseField.json
definitions/json/CaseTypeTab.json
definitions/json/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4045
Code change to add three doc collection tabs. This branch is also a rebase & has puled latest changes from Pet-1.2.2.
- [ x] commit messages are meaningful and follow good commit message guidelines

Three new tabs added

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Bundles-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Bundles-nonprod.json
definitions/json/CaseEvent/CaseEvent-Bundles-nonprod.json
definitions/json/CaseField/CaseField-Bundles-nonprod.json

https://tools.hmcts.net/jira/browse/RET-3092

RET-3092 Submit / CYA claimant bundles

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/ComplexTypes/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4062
Merge new event to master/aat
Note - only used in Rule 92 and won't be called in Prod yet

RET-4062 Event for AAT

---

definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4004
Permissions for data needed for Work Allocation.
Referral/Application Replies

RET-4004 WA enablers

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-CaseFlagsCaseLinking-nonprod.json
definitions/json/CaseEvent/CaseEvent-CaseFlagsCaseLinking-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4295
Add migration events for case flags

RET-4295 - Add migration events

---

definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4004
Added missing Publish

RET-4004: ReferralFix

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4378

RET-4378 Allow legal rep to CRU genericTseApplicationCollection 

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-HMC-nonprod.json

Adding HMC related fields
```
[] Yes
[x] No
```

RET-0000: Adding HMC related fields

---

definitions/json/CaseEvent/CaseEvent-HMC-nonprod.json
definitions/json/CaseEvent/CaseEvent-prod.json
definitions/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4382
Add callback to addAmendClaimantRepresentative for HMC
```
[] Yes
[x] No
```

RET-4382: Add callback to addAmendClaimantRepresentative for HMC

---

definitions/json/ComplexTypes/ComplexTypes-Bundles.json

https://tools.hmcts.net/jira/browse/RET-3082

RET-3082 rename field

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-HMC-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/CaseEvent/CaseEvent-HMC-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-HMC-nonprod.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-HMC-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-HMC-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-HMC-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed-HMC-nonprod.json

Party unavailability dates (HMC)
```
[] Yes
[x] No
```

RET-0000: Party unavailability dates (HMC)

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json
env.json

https://tools.hmcts.net/jira/browse/RET-4016
Added issueInitialConsiderationDirectionsWA event
```
[] Yes
[x] No
```

RET-4016: Added issueInitialConsiderationDirectionsWA event

---

definitions/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-4014
Publish CaseData

RET-4014: Publish CaseData

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4507
Add create lead case event

RET-4507 - Add create lead case event

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4016
https://tools.hmcts.net/jira/browse/RET-2435
Connect up RET-4016 & RET-2435

RET-4016: Connect up RET-4016 & RET-2435

---

definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

Fixing a duplicate element code

Fixing duplicate list element code

---

definitions/json/ComplexTypes/ComplexTypes-WA-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4515
Additional Field needed for WA

RET-4515: Additional Field needed for WA

---

definitions/json/CaseField/CaseField-Bundles-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4548
Remove 2500 character limit for some bundles text fields

RET-4548 Remove 2500 char limit

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-3296
Additional Authorisation

RET-3296: Add Authorisation

---

definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4517
Add additional triggering event for Et3Processing

RET-4517: Add triggering event for Et3Processing

---

definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-4346
ECC- Extra radio button to be added to What is the ECC notification

RET-4346 - Add ECC radio button

---

definitions/json/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4344
Update hint text

RET-4344-Update hint text

---

definitions/json/EventToComplexTypes/EventToComplexTypes.json

Added nested complexType field in EventToComplexType

Added nested complexType field in EventToComplexType

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-HMC-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-HMC-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed-HMC-nonprod.json

Added missing HMC fields from Release-2.2 branch
```
[] Yes
[x] No
```

RET-0000: Added missing HMC fields from Release-2.2 branch

---

definitions/json/ComplexTypes/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4393
Add responseState to pseRespondCollection

RET-4393-PSE- Display response from claimant

---

definitions/json/ComplexTypes/ComplexTypes-WA-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

###(https://tools.hmcts.net/jira/browse/RET-3991)
- [x ] README and other documentation has been updated / added (if needed)

adding -icListingPreliminaryHearing field

---

definitions/json/ComplexTypes/ComplexTypes-HMC-nonprod.json

Removing duplicate property that is now in WA

Removing duplicate property that is now in WA

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4635
Give WA access to Managing Office

RET-4635: Give WA access to Managing Office

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-4643
Added permissions for legalrep-solicitor for nextListedDate
```
[] Yes
[x] No
```

RET-4643: Added permissions for legalrep-solicitor for nextListedDate

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Bundles-nonprod.json
definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

Formatted JSON files
```
[] Yes
[x] No
```

RET-0000: Formatted JSON files

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4611
Added Docs, Claimant Docs and Respondent Docs for Multiples
```
[] Yes
[x] No
```

RET-4611: Added Docs, Claimant Docs and Respondent Docs for Multiples

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/COT-708
https://tools.hmcts.net/jira/browse/COT-731
RAS Validation is missing access to the Case Region
Also removed a duplicate entry in EventToComplexTypes

COT-708-731: Give RAS access to Case Region

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-WA-nonprod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-prod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles.json

https://tools.hmcts.net/jira/browse/RET-4676
Add missing SA and CA, also update access profiles

RET-4676: Add missing SA and CA, also update access profiles

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-4686
add notification tab

RET-4686-add notification tab

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-prod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles.json

https://tools.hmcts.net/jira/browse/RET-4681
Removed some Idam mapping as was granting Users with this role Standard Access to cases

RET-4681: Remove global Standard Access roles

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4700
Add applications tab

RET-4700 - Add applications tab

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4701
Add referrals tab

RET-4701 - Add referrals tab

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json

Removing duplicate properties

---

definitions/json/ComplexTypes/ComplexTypes.json

Remove show condition

---

definitions/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-4748
Make further info optional

RET-4748 - Make further info optional

---

definitions/json/CaseEvent/CaseEvent-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-prod.json
definitions/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/RET-4718
Publishing amendCaseDetails for WA
```
[] Yes
[x] No
```

RET-4718: Publishing amendCaseDetails for WA

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-WA-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
definitions/json/CaseEvent/CaseEvent-WA-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-WA-nonprod.json
definitions/json/CaseField/CaseField-WA-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-WA-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-prod.json
definitions/json/CaseTypeTab/CaseTypeTab.json
definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4740
Create DraftAndSignJudgement event

RET-4740 - Create DraftAndSignJudgement event

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4699
Enable upload document

RET4699-V2-ENABLE-UPLOAD-DOCUMENT

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4741
Remove legal rep access and add caseworker

RET-4741 - Remove legal rep access and add caseworker access

---

definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-prod.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4784
Publish hearingDetailsStatus

RET-4784 - Publish hearingDetailsStatus

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4687
Add leadCaseId

RET-4687 - Add leadCaseId

---

definitions/json/EventToComplexTypes/EventToComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4752
Publish isJudgement for WA

RET-4752: Publish isJudgement for WA

---

definitions/json/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/RET-4728
acas email corrected
- [ x] commit messages are meaningful and follow good commit message guidelines

acas email corrected

---

definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4741
Update LegalOps access to include Judges Tasks

RET-4741: Update for LegalOps to do Judge Task

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4250
Add Case Stayed option to batch update
```
[] Yes
[x] No
```

RET-4250: Add Case Stayed option to batch update

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4705
replyToReferrals for Multiples
```
[] Yes
[x] No
```

RET-4705: replyToReferrals for Multiples

---

definitions/json/ComplexTypes/ComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4864
Hide Internal WA Fields from ExUI

RET-4864: Hide Internal WA Fields from ExUI

---

definitions/json/ComplexTypes/ComplexTypes-WA-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4864
Hide WA Only Internal Fields from EXUI

RET-4864: Hide WA Only Internal Fields from EXUI

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4711
Send notification to all

RET-4711 - Send notification to all

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4743
Add notificationSentFrom

RET-4743 - Add notificationSentFrom

---

definitions/json/CaseEvent/CaseEvent.json
definitions/json/ComplexTypes/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-4294
- Removed unnecessary update referral callback
- Change text from referred to updated
- Reordered update to be above replies

RET-4294 - Update referral changes

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4704
Update ReplyToReferral and UpdateReferral
```
[] Yes
[x] No
```

RET-4704: Update ReplyToReferral and UpdateReferral

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4715
Batch send notifications

RET-4715 - Add batch processing to send notification

---

definitions/json/CaseTypeTab/CaseTypeTab-WA.json

Removing e from Judgement

---

definitions/json/ComplexTypes/ComplexTypes-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json

https://tools.hmcts.net/jira/browse/RET-4926
Add a counter so that the ET3 Processing Task would only trigger once.

RET-4926: New Counter for WA Task

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-WA.json
definitions/json/CaseEvent/CaseEvent-WA.json

https://tools.hmcts.net/jira/browse/RET-5020
https://tools.hmcts.net/jira/browse/RET-5026
- Added Rejected as a precondition state for amendRespondentDetails
- Add extra permissions for draftAndSignJudgment event

RET-5020 and 5026

---

definitions/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-5037
Remove dependancy on CMO being selected for showing response required and select parties fields
```
[] Yes
[x] No
```

RET-5037: Remove dependancy on CMO being selected for showing response required and select parties fields

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-HMC-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json
definitions/json/CaseField/CaseField-HMC-nonprod.json
definitions/json/CaseField/CaseField-WA.json

Add CaseManagementLocationCode to WA

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4732
Add notifications extract

RET-4732 - Add notifications extract

---

definitions/json/EventToComplexTypes/EventToComplexTypes-ECC-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5038
Publish et3ContractClaimSection7

RET-5038 - Publish et3ContractClaimSection7

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-Multiples-nonprod.json
yarn.lock

https://tools.hmcts.net/jira/browse/RET-5053
Add case note feature

Ret 5053 - Add case note feature

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/AuthorisationCaseState/AuthorisationCaseState-Multiples-nonprod.json
definitions/json/AuthorisationCaseType/AuthorisationCaseType-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseRoles/CaseRoles.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/RoleToAccessProfiles/RoleToAccessProfiles-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-4678
Grant Legal Rep access to a Multiple if they are assigned to a sub-case.

RET-4678: Grant Legal Rep access to a Multiple

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5064
Add DCF to multiple

RET-5064 - Add DCF to multiple

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

Update case note

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/RET-5181
case field authorisation updated for legal rep
- [x ] commit messages are meaningful and follow good commit message guidelines

legal rep authorisation updated

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5118
Add caseManagementLocation to multiple

RET-5118 - Add caseManagementLocation to multiple

---

definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5196
Change text of button for Referral Events

RET-5196: Change text of button for Referral Events

---

definitions/json/ComplexTypes/ComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-5206
Add author

RET-5206 - Add author

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed-Multiples-nonprod.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-5205
RET-5205: Remove sub-case from Multiple with using Batch Process

RET-5205: Remove Subcase from Multiple

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5205
Authorisation CaseField

RET-5205: Authorisation CaseField

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent-Multiples-prod.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5258
Update based on testing

RET-5258: Update Authorisation and AdditionalFields

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5205
Fix Typo in Authorisation

RET-5205: Fix Typo in Authorisation

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields-Multiples-nonprod.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5232
Added jurisdictions list
```
[] Yes
[x] No
```

RET-5232: Added jurisdictions list

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5258
All WA to see MultipleName

RET-5258: Allow WA Access to Multiple name

---

definitions/json/CaseField/CaseField-Multiples-nonprod.json

https://tools.hmcts.net/jira/browse/RET-5232
Fix for DynamicListCollection
```
[] Yes
[x] No
```

RET-5232: Fix for DynamicListCollection

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEventToFields/CaseEventToFields.json

Fix Legal rep doc access in Scotland

Fix Legal rep doc access in Scotland

---

definitions/json/CaseEvent/CaseEvent-WA.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField-WA.json
definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

[See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/RET-5257)
- Functionality to add multiple documents in draft and sign event

Judge's draft and sign document retention

---

definitions/json/ComplexTypes/ComplexTypes.json

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Restore old field for payload

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField-WA.json
definitions/json/CaseTypeTab/CaseTypeTab.json
definitions/json/ComplexTypes/ComplexTypes-Bundles.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
https://tools.hmcts.net/jira/browse/RET-5222
- added functionality for document upload in initial consideration

ic configs for scotland

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField.json
definitions/json/ComplexTypes/ComplexTypes-ET3-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-HMC-nonprod.json
definitions/json/EventToComplexTypes/EventToComplexTypes-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

https://tools.hmcts.net/jira/browse/RET-5437
Respondent hearing panel reference fields added
- [x ] commit messages are meaningful and follow good commit message guidelines

ret-5437 implementation

---

definitions/json/CaseField/CaseField-Bundles.json
definitions/json/CaseField/CaseField-CaseFileView.json
definitions/json/CaseField/CaseField-CaseFlagsCaseLinking.json
definitions/json/CaseField/CaseField-DCF2.json
definitions/json/CaseField/CaseField-ET1Repped.json
definitions/json/CaseField/CaseField-Rule92.json
definitions/json/CaseField/CaseField-WA.json
definitions/json/CaseField/CaseField.json
definitions/json/ComplexTypes/ComplexTypes-Bundles.json
definitions/json/ComplexTypes/ComplexTypes-ET1Repped.json
definitions/json/ComplexTypes/ComplexTypes-ET3-nonprod.json
definitions/json/ComplexTypes/ComplexTypes-WA.json
definitions/json/ComplexTypes/ComplexTypes-prod.json
definitions/json/ComplexTypes/ComplexTypes.json

Introducing https://tools.hmcts.net/confluence/display/RCCD/Configuring+Searchable+column

Searchable

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent-EcmMigration-nonprod.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField-EcmMigration-nonprod.json
definitions/json/CaseEvent/CaseEvent-EcmMigration-nonprod.json
definitions/json/CaseField/CaseField-EcmMigration-nonprod.json
definitions/json/CaseTypeTab/CaseTypeTab-EcmMigration-nonprod.json

See [RET-247](https://tools.hmcts.net/jira/browse/RET-247)
Added non prod files for ECM -> RET migration

ECM->RET migration

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json

https://tools.hmcts.net/jira/browse/RET-5733
Add WA permissions to claimant and respondent fields

Add WA permissions to fields

---

definitions/json/Categories/Categories-Multiples.json
definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

See [RET-5730](https://tools.hmcts.net/jira/browse/RET-5730)
- Added new doc type
- Split categories into singles and multiples file

RET-5730 - New doc type

---

definitions/json/EventToComplexTypes/EventToComplexTypes.json

See [RET-5736](https://tools.hmcts.net/jira/browse/RET-5736)
Make document types mandatory when adding a document

RET-5736 - Doc category mandatory

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseField/CaseField.json

See [RET-5764](https://tools.hmcts.net/jira/browse/RET-5764)
Added new field for ACAS Cert Cron Job

New Acas Doc field

---

definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/RET-5790

change ADR -> ADR/Privileged

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

https://tools.hmcts.net/jira/browse/RET-5628
Casedata fields published to be used as input for setting the draft and sign judgment due date.
- [ x] commit messages are meaningful and follow good commit message guidelines

draft and sign judgment due date input published

---

definitions/json/Scotland Scrubbed/Scotland Scrubbed.json

See [RET-5874](https://tools.hmcts.net/jira/browse/RET-5874)
Update Scotland letters

Remove some letters from the drop down options

---

definitions/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/json/CaseEvent/CaseEvent-Multiples-nonprod.json
definitions/json/CaseEvent/CaseEvent.json
definitions/json/CaseEventToFields/CaseEventToFields.json
definitions/json/CaseField/CaseField.json
definitions/json/CaseTypeTab/CaseTypeTab.json
definitions/json/ComplexTypes/ComplexTypes-Multiples-nonprod.json
definitions/json/ComplexTypes/ComplexTypes.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

See [RET-5931](https://tools.hmcts.net/jira/browse/RET-5931)
Added CaseNotes
Refactored existing multiples code to work with Singles

Add 'Add Case Note' functionality for ET_Scotland case type

---

definitions/json/CaseEvent/CaseEvent-HMC-nonprod.json
definitions/json/CaseEvent/CaseEvent-HMC-prod.json

https://tools.hmcts.net/jira/browse/RET-5954
https://tools.hmcts.net/jira/browse/RET-5955
https://tools.hmcts.net/jira/browse/RET-5956

Amend add delete claimant rep

---

definitions/json/AuthorisationCaseField/AuthorisationCaseField-WA.json

See [RET-5933](https://tools.hmcts.net/jira/browse/RET-5933)
See [RET-5934](https://tools.hmcts.net/jira/browse/RET-5934)
See [RET-5935](https://tools.hmcts.net/jira/browse/RET-5935)
Give WA permission to view ethosCaseReference to allow it to be used in caseName (see https://github.com/hmcts/et-wa-task-configuration/pull/386)

RET-5933-35

---

definitions/json/CaseEventToFields/CaseEventToFields-WA-hearingdate.json
definitions/json/CaseEventToFields/CaseEventToFields-WA.json
definitions/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RET-5798
fields display index re-ordered

ic 2nd page display re-organised

---

definitions/json/CaseTypeTab/CaseTypeTab.json
definitions/json/ComplexTypes/ComplexTypes-ET3.json
definitions/json/EventToComplexTypes/EventToComplexTypes.json

Field added on the respondent details event and respondents tab
https://tools.hmcts.net/jira/browse/RET-6022
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

RET-6022 - add field for ECC Reply
